services:
  hufpflege:
    image: hufpflege
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - db
  express:
    build:
      context: ./express-app
      dockerfile: Dockerfile
    image: metaphysiker/ws_mgr_express:development
    env_file:
      - .env
    ports:
      - "${PORT_BACKEND}:3000"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    volumes:
      - mongodata:/data/db
    env_file:
      - .env
