services:
  hufpflege:
    image: hufpflege
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - hufpflegedbdata:/var/lib/mysql

volumes:
  hufpflegedbdata:
