services:
  vue:
    build:
      context: ../../vue-app
      dockerfile: Dockerfile
      target: development-stage
      args:
        VITE_API_BASE_URL: "${API_BASE_URL}"
    volumes:
      - ../../vue-app/src:/app/src
    env_file:
      - .env
    ports:
      - "${PORT_FRONTEND}:8080"
  nest:
    build:
      context: ../../nest-app
      dockerfile: Dockerfile
      target: development-stage
    volumes:
      - ../../nest-app/src:/app/src
    env_file:
      - .env
    ports:
      - "${PORT_BACKEND}:3001"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - hufpflegedbdata:/var/lib/mysql
  npm:
    build: ../../tools/npm
    volumes:
      - ../../:/app
    user: "${UID}:${GID}"

volumes:
  hufpflegedbdata:
